# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet_name', models.CharField(max_length=20)),
                ('snippet_privacy', models.BooleanField(default=False)),
                ('snippet_expiry', models.CharField(max_length=3)),
                ('snippet_file', models.CharField(max_length=1000)),
            ],
        ),
    ]
